# The language of the plugin
# Please make sure the file exists in the /lang folder
lang: zh_cn

# Nation-related settings
nation:
  creation-cost: 500 # The cost of creating a nation
  capital-name: "%nation%首都"
  claim-cost: 10 # The cost of claiming a chunk
  unclaim-refund: 8 # The refund of unclaiming a chunk

# Town-related settings
town:
  creation-cost: 100 # The cost of creating a town
  claim-cost: 30 # The (additional) cost of claiming a chunk as a town chunk
  unclaim-refund: 10 # The refund of unclaiming a chunk as a town chunk

border-display: # [Most options in this section require restart to take effect]
  nation-border: true
  town-border: true

  range: 3 # in chunks
  interval: 15 # in ticks
  particle-size: 1.5

combat:
  damage-units: 10 # top 10 units are counted toward the stack's total damage

  transport-mob: zombie
  army-tick-interval: 1200 # How long in game ticks does all of the armies update? This can change the speed of many things related to army such as combat speed
  transport-max-distance: 16 # The unit must be within 16 blocks of the army
  transport-warn-distance: 12 # The unit must be within 16 blocks of the army