# It is suggested to increase the bukkit.yml health limit to around 100,000!

# The language of the plugin
# Please make sure the file exists in the /lang folder
lang: zh_cn

# Nation-related settings
nation:
  creation-cost: 500 # The cost of creating a nation
  capital-name: "%nation%首都"
  claim-cost: 10 # The cost of claiming a chunk
  unclaim-refund: 8 # The refund of unclaiming a chunk

# Town-related settings
town:
  creation-cost: 100 # The cost of creating a town
  claim-cost: 30 # The (additional) cost of claiming a chunk as a town chunk
  unclaim-refund: 10 # The refund of unclaiming a chunk as a town chunk
  teleport-countdown: # The countdown for /k tp

map:
  width: 6 # This value *2+1 is the actual size of the map
  height: 4 # This value *2+1 is the actual size of the map

border-display: # [Most options in this section require restart to take effect]
  nation-border: true
  town-border: true

  range: 3 # in chunks
  interval: 15 # in ticks
  particle-size: 1.5

combat:
  damage-units: 10 # top 10 units are counted toward the stack's total damage
  defend-units: 10 # 10 entities can be spawned at the same time to defend camps/invasions

  chunk-hp: 10 # How many hp does a single chunk have

  transport-mob: zombie
  army-tick-interval: 10 # How long in seconds does all of the combats update?
  transport-max-distance: 64 # The unit must be within 64 blocks of the player, or else its gonna be destroyed
  transport-warn-distance: 56